HalloDoc/Controllers/PhysicianDashboardController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using HalloDoc.BussinessAccess.Repository.Interface;
using HalloDoc.DataAccess.Data;
using HalloDoc.DataAccess.Models;
using HalloDoc.DataAccess.ViewModel;
using HalloDoc.DataAccess.ViewModel.AdminViewModel;
using HalloDoc.DataAccess.ViewModel.ProvidersMenu;
using HalloDoc.Services;
using HalloDoc.DataAccess.utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Options;
using NuGet.Protocol;
using Rotativa.AspNetCore;
using System.Drawing;
using System.IdentityModel.Tokens.Jwt;
using Twilio.Rest.Taskrouter.V1.Workspace.TaskQueue;
using Twilio.TwiML.Voice;
using AspNetCore;
using HalloDoc.DataAccess.ViewModel.PhysicianDashboard;
using System.Drawing.Printing;

namespace HalloDoc.Controllers
{
    [CustomAuth("Provider")]
    public class PhysicianDashboardController : Controller
    {
        private readonly IAdminDashboardRepository _adminRepo;
        private readonly IPhysicianSiteRepository _phyRepo;
        private readonly IRequestRepository _requestRepo;
        private readonly IProviderMenuRepository _providerRepo;
        private readonly ILoginRepository _loginRepo;
        private readonly ICommonRepository _common;
        private readonly IJwtService _jwtService;
        private readonly INotyfService _notyf;
        private readonly ISMSSender _sms;
        public PhysicianDashboardController(IPhysicianSiteRepository phyRepo, IJwtService jwtService, INotyfService notyf, ILoginRepository loginRepo, IRequestRepository requestRepo, ISMSSender sms, ICommonRepository common, IProviderMenuRepository providerRepo, IAdminDashboardRepository adminRepo)
        {
            _notyf = notyf;
            _phyRepo = phyRepo;
            _jwtService = jwtService;
            _loginRepo = loginRepo;
            _requestRepo = requestRepo;
            _sms = sms;
            _common = common;
            _providerRepo = providerRepo;
            _adminRepo = adminRepo;
        }
        public string GetAspID()
        {
            var token = Request.Cookies["jwt"];
            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
            string AspId = jwt.Claims.First(c => c.Type == "AspId").Value;

            return AspId;
        }
        public string GetName()
        {
            var token = Request.Cookies["jwt"];
            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
            string fname = jwt.Claims.First(c => c.Type == "firstName").Value;
            string lname = jwt.Claims.First(c => c.Type == "lastName").Value;
            return fname + "_" + lname;
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public void PhysicianLocationUpdate(double latitude, double longitude)
        {
            bool x = _phyRepo.PhysicianLocationUpdate(latitude, longitude, _phyRepo.GetPhysicianId(GetAspID()));
        }

        #region PhysicianDashboard

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult Dashboard(int? status)
        {
            var token = Request.Cookies["jwt"];
            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
            string fname = jwt.Claims.First(c => c.Type == "firstName").Value;
            string lname = jwt.Claims.First(c => c.Type == "lastName").Value;
            string AspId = GetAspID();
            ViewBag.AdminName = GetName();
            var dashData = new AdminDashboardViewModel
            {
                status = status,
                countRequestViewModel = _phyRepo.DashboardCount(_phyRepo.GetPhysicianId(AspId)),
                Region = _phyRepo.GetRegion()
            };
            return View(dashData);
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        [HttpPost]
        public async Task<IActionResult> PartialTable(int status, searchViewModel? obj, int pageNumber)
        {
            var phyId = _phyRepo.GetPhysicianId(GetAspID());
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }
            int pageSize = 2;
            if (status == (int)enumsFile.DashboardStatus.newStatus)
            {
                var parseData = _phyRepo.newReq(obj, phyId);
                //return PartialView("_newRequestView", parseData);
                return PartialView("_newRequestView", await PaginatedList<pendingReqViewModel>.CreateAsync(parseData, pageNumber, pageSize));
            }
            else if (status == (int)enumsFile.DashboardStatus.pending)
            {
                var parseData = _phyRepo.pendingReq(obj, phyId);
                return PartialView("_PendingRequestView", await PaginatedList<pendingReqViewModel>.CreateAsync(parseData, pageNumber, pageSize));
            }
            else if (status == (int)enumsFile.DashboardStatus.active)
            {
                var parseData = _phyRepo.activeReq(obj, phyId);
                return PartialView("_activeRequestView", await PaginatedList<pendingReqViewModel>.CreateAsync(parseData, pageNumber, pageSize));
            }
            else if (status == (int)enumsFile.DashboardStatus.conclude)
            {
                var parseData = _phyRepo.concludeReq(obj, phyId);
                return PartialView("_concludeReqView", await PaginatedList<pendingReqViewModel>.CreateAsync(parseData, pageNumber, pageSize));
            }

            return View();
        }


        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult SendEmailToPatient(string FirstName, string LastName, string Email, string PhoneNumber)
        {
            var subject = "Send your request";
            var body = "<a href='/HomeController/Index+'>HalloDoc</a>";
            _loginRepo.SendEmail(Email, subject, body, null);
            Task<bool> val = _sms.SendSmsAsync("+91" + PhoneNumber, body);

            return RedirectToAction("Dashboard");
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult CreateRequest()
        {
            string AspId = GetAspID();
            ViewBag.AdminName = GetName();
            var data = new PatientViewModel()
            {
                Regions = _requestRepo.Regions()
            };
            return View(data);
        }

        [HttpPost]
        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult CreateRequest(PatientViewModel obj)
        {

            if (ModelState.IsValid)
            {
                _requestRepo.CreateRequestByPhysician(obj, _phyRepo.GetPhysicianId(GetAspID()));

                return RedirectToAction("Dashboard");
            }
            return View();
        }

        #endregion

        #region DashboardAction

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult AcceptRequest(int id)
        {
            bool x = _phyRepo.AccpetRequest(id);
            if (x)
            {
                _notyf.Success("Request has been Accepted");
                return RedirectToAction("Dashboard");
            }
            else
            {
                _notyf.Error("Something went wrong");
                return RedirectToAction("Dashboard");
            }
        }
        [HttpPost]
        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public void SendAgreement(int reqClientId, string email, string phone)
        {

            var callBackUrl = Url.Action("ReviewAgreement", "Home", new { reqClientId }, protocol: HttpContext.Request.Scheme, host: "localhost:44349");

            string subject = "Regarding Agreement";
            string body = "<a href=" + callBackUrl + ">Review</a>";

            _loginRepo.SendEmail(email, subject, body, null);
        }

        [HttpPost]
        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult TransferCase(string addNote, int reqClientId)
        {
            _phyRepo.TransferCase(reqClientId, addNote);
            return Ok(new { success = true });
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult ViewCase(int reqClientId)
        {
            ViewBag.AdminName = GetName();
            var viewdata = _adminRepo.viewCase(reqClientId);

            return View(viewdata);
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult ViewNote(int reqClientId)
        {
            ViewBag.AdminName = GetName();
            var data = _adminRepo.ViewNoteGet(reqClientId);

            return View(data);
        }
        [HttpPost]
        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult ViewNote(string adminNote, int reqClientId)
        {
            string aspId = GetAspID();
            int phyId = _phyRepo.GetPhysicianId(GetAspID());
            _phyRepo.ViewNotePost(reqClientId, adminNote, phyId, aspId);

            return RedirectToAction("ViewNote", new { reqClientId = reqClientId });
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult ViewUpload(int reqClientId)
        {
            string AspId = GetAspID();
            ViewBag.AdminName = GetName();
            int physicianId = _phyRepo.GetPhysicianId(AspId);
            var data = _adminRepo.ViewUpload(reqClientId);
            return View(data);
        }

        [RoleAuth((int)enumsFile.physicianRoles.Dashboard)]
        public IActionResult UploadDocument(UploadFileViewModel obj)
        {
            var phyId = _phyRepo.GetPhysicianId(GetAspID());
            int id = _adminRepo.GetReqId(obj.reqId);
            if (obj.formFile != null && obj.formFile.Length > 0)
            {
                _loginRepo.uploadFile(obj.formFile, "RequestData\\" + obj.reqId, obj.formFile.FileName.ToString());
                _phyRepo.viewUplodPost(obj.formFile.FileName, obj.reqId, phyId);
                _notyf.Success("File uploaded.");
            }

HalloDoc/Views/PhysicianDashboard/ConcludeCare.cshtml
@model HalloDoc.DataAccess.ViewModel.AdminViewModel.CloseCaseViewModel;
@{
    ViewData["Title"] = "Conclude Care";
    Layout = "_PhysicianLayout";
}

<div class="container">
    <div class="d-flex justify-content-between mt-5">
        <h3>
            Conclude Care
        </h3>
        <a href="@Url.Action("Dashboard", "PhysicianDashboard", new{status = Model.status})"
           class="btn btn-outline-primary m-2 text-decoration-none float-end" id="back-btn">
            <img src="~/images/arrow_back_ios_FILL0_wght400_GRAD0_opsz24.svg" class="img-fluid" alt="">
            Back
        </a>
    </div>
    <div class="p-3 shadow">
       
        <div class="d-flex justify-content-between">
            <div>
                <span>Patient Name</span>
                <p>
                    <span class="fs-4" style="color: #01bce9">@Model.Firstname @Model.Lastname </span>(@Model.confirmationNo)
                </p>
            </div>
        </div>
        <form method="post" asp-action="ConcludeCare" asp-controller="PhysicianDashboard" enctype="multipart/form-data">
        <div class="d-flex justify-content-between m-1">
            <h4>Encounter Forms</h4>
            <input asp-for="ReqClientId" value="@Model.ReqClientId" hidden/>
            <input id="encounterForm" asp-for="fileName" type="file" class="form-control" hidden required>
            <label class="input-group-text btn btn-primary" id="uploadFileLabel1" for="encounterForm">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud-arrow-up" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M7.646 5.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 6.707V10.5a.5.5 0 0 1-1 0V6.707L6.354 7.854a.5.5 0 1 1-.708-.708z" />
                    <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383m.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z" />
                </svg>
                Upload
            </label>
        </div>

        <div class="d-md-none">
            @foreach (var item in Model.PatientDocumentViewModel)
            {
                @if (item.IsDeleted != true)
                {
                    <div>
                        <div>
                            <span class="FileName">
                                @item.Filename
                            </span>
                        </div>
                        <span class="">@item.createdate</span><br />
                        <span class="">
                            <input value="@item.ReqClientId" class="ReqClientId" hidden>
                            <a href="/uploadedFiles/@item.Filename" class="btn btn-outline-primary" download>
                                <img id="uploadFile" src="~/images/cloud-arrow-down.svg" />
                            </a>
                        </span>
                    </div>
                }
            }
            <div>
            </div>
        </div>

        <table class="table d-none d-md-table">
            <thead>
                <tr class="m-0 p-0 table-secondary">
                    <th colspan="2">document</th>
                    <th>Upload Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PatientDocumentViewModel)
                {
                    @if (item.IsDeleted != true)
                    {
                        <tr class="m-0 p-0">
                            <td colspan="2" class="FileName">@item.Filename</td>
                            <td>@item.createdate</td>
                            <td>
                                <input value="@item.ReqClientId" class="ReqClientId" hidden>
                                <a href="/uploadedFiles/@item.Filename" class="btn downloadFile"
                                   style="color: #01bce9; border: 1px solid #01bce9;" download>
                                    <img id="uploadFile" src="~/images/cloud-arrow-down.svg" />
                                </a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
       
            <h4 class="mt-4 mb-4 ms-2">Providers Notes</h4>
            <div class="row g-2 m-1">
                <textarea asp-for="note" class="form-control" placeholder="Provider Note"
                          style="height: 100px"></textarea>
            </div>
                <button type="submit" class="btn btn-primary float-end m-1">Conclude Care</button><br /><br />
        </form>
    </div>
</div>

@section AdminScript {
    <script>
       
    </script>
}

HalloDoc/Views/PhysicianDashboard/ViewCase.cshtml
@model HalloDoc.DataAccess.ViewModel.AdminViewModel.viewCaseViewModel;
@{
    ViewData["Title"] = "View Case";
    Layout = "_PhysicianLayout";
}
<div class="tab-pane fade show" id="tab2">
    <div class="container d-flex justify-content-between mt-4" style="max-width:1000px">
        
        <h4>New Request 
            <span class="border bg-success rounded-pill h-50 fs-6 p-1 text-white">Patient</span>
        </h4>
        <a href="@Url.Action("Dashboard","PhysicianDashboard")" class="btn btn-outline-primary m-2 text-decoration-none float-end"
           id="back-btn">
            <img src="~/images/arrow_back_ios_FILL0_wght400_GRAD0_opsz24.svg" class="img-fluid" alt="">
            Back
        </a>
    </div>
    <div class="container-fluid d-flex justify-content-center mt-4">
        @if(ViewBag.error != null)
        {   
        <span>@ViewBag.error</span>
        }
        @if (ViewBag.success != null)
        {
            <span>@ViewBag.success</span>
        }
        <form  method="post" asp-action="ViewCase" class="viewCaseForm form-floating shadow patient-request-form p-3">

                <h5>Patient Information</h5>
                <input name="Requestclientid" value="@Model.Requestclientid" type="hidden" disabled/>
                <div>
                    <span style="font-size: 10px;">Confirmation Number</span><br />
                    <span class="fw-bold" style="color: #10bce9" >@Model.confirmationNumber</span>
                </div>
                <div class="form-floating m-1 form-div">
                    <textarea asp-for="Notes" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                          style="height: 100px" disabled></textarea>
                    <label for="">Patient Note</label>
                </div>
                <div class="row g-2 m-1">
                    <div class="col-md">
                        <div class="form-floating">
                            <input asp-for="Firstname" type="text" class="form-control" placeholder="" disabled>
                            <label for="">First Name</label>
                        </div>
                        <span asp-validation-for="Firstname"></span>
                    </div>
                    <div class="col-md">
                        <div class="form-floating">
                        <input asp-for="Lastname" type="text" class="form-control" placeholder="" disabled>
                            <label for="floatingSelectGrid">Last Name</label>
                        </div>
                        <span asp-validation-for="Lastname"></span>
                    </div>
                </div>

                <div class="row g-2 m-1">
                    <div class="col-md-6">
                        <div class="form-floating">
                        <input asp-for="Strmonth" type="date" class="form-control" placeholder="" disabled>
                            <label for="">Date Of Birth</label>
                        </div>
                        <span asp-validation-for="Strmonth"></span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-floating phone-div w-100">
                        <input asp-for="Phonenumber" type="tel" class="form-control w-100 h-100 inputDis" id="patientPhone" placeholder="" disabled>
                            <label for=""></label>
                        </div>
                        <span asp-validation-for="Phonenumber"></span>
                    </div>
                    <div class="col-md-1">
                        <a href="tel:@Model.Phonenumber" class="btn btn-outline-primary form-floating d-flex align-items-center justify-content-center rounded h-100 w-100" >
                            @*<img src="~/images/telephone.svg"/>*@
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z" />
                        </svg>
                        </a>
                    </div>
                </div>

                <div class="row g-2 m-1">
                    <div class="col-md-6">
                        <div class="form-floating">
                        <input asp-for="Email" id="checkEmail" type="email" class="form-control inputDis" placeholder="name@example.com" disabled>
                            <label for="">Email</label>
                        </div>
                        <span asp-validation-for="Email"></span>
                    </div>
                </div>

                <h5>Location Information</h5>
                <div class="row g-2 m-1">
                    <div class="col-md-6">
                        <div class="form-floating">
                        <input type="text" class="form-control" placeholder="" disabled>
                            <label for="">Regoin</label>
                        </div>
                        <span></span>
                    </div>
                    <div class="col-md-5">
                        <div class="form-floating">
                        <input type="text" class="form-control" placeholder="" disabled>
                            <label for="">Business Name/ Address</label>
                        </div>
                        <span></span>
                    </div>
                    <div class="col-md-1">
                    <a target="_blank" href="http://maps.google.com/?q= +@Model.State + @Model.City + @Model.Street"
                       class="btn btn-outline-primary form-floating d-flex align-items-center justify-content-center rounded h-100 w-100">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                            <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10" />
                            <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                        </svg>
                    </a>
                    </div>
                    <div class="col-md-6">
                        <div class="form-floating">
                            <input type="text" class="form-control" placeholder="" disabled>
                            <label for="">Room #</label>
                        </div>
                        <span ></span>
                    </div>
                </div>
            @if(Model.status == 1)
            {   
                <a  class="btn btn-success float-end m-1 " asp-action="AcceptRequest" asp-route-id="@Model.Requestclientid">Accept</a>
            }
            <a type="button" href="@Url.Action("ViewNote", new{reqClientId = Model.Requestclientid})" id="viewNoteBtn" class="btn btn-primary float-end m-1">View Notes</a>

            
        </form>
    </div>
</div>


@section AdminScript {
    <!-- js ans css for phone input -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous">
    </script>
    <script src="~/js/admin.js"></script>
}

HalloDoc/Views/PhysicianDashboard/_FinalizedPopUp.cshtml
@model Encounter;
<div class="modal  fade" id="FinalizedPopUp" tabindex="-1" aria-labelledby="newReqModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <input value="" id="EncounterId" hidden />
            <div class="modal-header" style="background-color: #01bce9; color:white;">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Encounter Form</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Encounter Form is finalized successfully!</p>

            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" asp-action="downloadFinalEncounter" asp-controller="PhysicianDashboard" asp-route-id="@Model.EncounterId">Download</button>
            </div>
        </div>
    </div>
</div>

<script>

</script>

HalloDoc/Views/PhysicianDashboard/_ViewShift.cshtml
@model CreateShift;
<div class="modal fade CreateShiftModel" id="VieShiftModel" tabindex="-1" aria-labelledby="newReqModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #01bce9; color:white;">
                <h1 class="modal-title fs-5" id="exampleModalLabel">View Shift</h1>
                <button type="button" class="btn-close closeBtn" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="dropdown">
                    <form id="ViewShiftForm" asp-action="UpdateShift" asp-controller="PhysicianDashboard" asp-route-id="@Model.ShiftDetailId">
                        <fieldset id="fieldset" disabled>
                            <select asp-for="Regionid" class="form-select form-select mb-3  RegionSelect" id="RegionSelect" aria-label="Large select example">
                                <option value="0">Select Region</option>
                                @foreach (var item in Model.Regions)
                                {
                                    if (item.Regionid == Model.Regionid)
                                    {
                                        <option value="@item.Regionid" selected>@item.Name</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Regionid">@item.Name</option>
                                    }
                                }
                            </select>
                            <span class="text-danger" asp-validation-for="Regionid"></span>
                            <div class="row g-2">
                                <div class="col-12">
                                    <div class="form-floating">
                                        <input asp-for="Startdate" type="date" value="@Model.Startdate.ToString("yyyy-MM-dd")" min="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" placeholder="">
                                        <label for="">ShiftDate</label>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-floating">
                                        <input asp-for="StartTime" id="StartTime" type="time" class="form-control" placeholder="">
                                        <label for="">start</label>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-floating">
                                        <input asp-for="EndTime" id="EndTime" type="time" class="form-control" placeholder="">
                                        <label for="">End</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <span class="text-danger" id="timeError"></span>
                                </div>
                            </div>
                        </fieldset><br />
                        @if (Model.status != 2)
                        {
                            @if (Model.Startdate >= DateOnly.FromDateTime(DateTime.Now))
                            {
                            <button type="reset" class="btn btn-primary d-none me-1 float-end" id="cancelBtn" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary me-1 d-none float-end" id="saveBtn">Save</button>
                            <button type="button" class="btn btn-danger me-1 float-end" id="deleteBtn" data-id="@Model.ShiftDetailId">Delete</button>
                            <button type="button" class="btn btn-primary me-1 float-end" id="editBtn" data-id="@Model.ShiftDetailId">Edit</button>

                                <button type="button" class="btn btn-primary me-1 float-end" id="reurnBtn" data-id="@Model.ShiftDetailId">Return</button>
                            }
                        }
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $("#editBtn").click(function () {
        $("#fieldset").prop('disabled', false);
        $("#cancelBtn").removeClass('d-none');
        $("#saveBtn").removeClass('d-none');
        $(this).addClass('d-none');
    })

    $("#deleteBtn").click(function () {
        var id = $(this).data('id');

        $.ajax({
            url: '/PhysicianDashboard/DeleteShift',
            type: 'POST',
            data: { shiftDetailId: id },
            success: function () {
                $("#VieShiftModel").modal('toggle');
                location.reload();
            }
        })
    })

    $("#reurnBtn").click(function () {
        var id = $(this).data('id');

        $.ajax({
            url: '/PhysicianDashboard/ReturnShift',
            type: 'POST',
            data: { shiftDetailId: id },
            success: function () {
                $("#VieShiftModel").modal('toggle');
                location.reload();
            }
        })
    })

    $(".closeBtn").click(function () {
        $("#VieShiftModel").modal('toggle');
    })

    $(".RegionSelect").change(function () {
        var selectedRegion = $(this).val();

        if (selectedRegion == null || selectedRegion == 0) {
            document.getElementById("RegionSelect").nextElementSibling.textContent = "Select Region!!"
        } else {
            document.getElementById("RegionSelect").nextElementSibling.textContent = "";
        }
    });

    $("#StartTime").change(function () {
        var EndTime = $(this).val();
        var startTime = $("#EndTime").val();
        if (startTime <= EndTime) {
            $("#timeError").text("Select Proper Time!!");
            $("#saveBtn").attr('disabled', 'disabled');
            console.log("error")
        } else {
            console.log("error n")
            $("#saveBtn").removeAttr('disabled');
            $("#timeError").text("");
        }
    })
    $("#EndTime").change(function () {
        var EndTime = $(this).val();
        var startTime = $("#StartTime").val();
        if (startTime >= EndTime) {
            $("#timeError").text("Select Proper Time!!");
            $("#saveBtn").attr('disabled', 'disabled');
            console.log("error")
        } else {
            console.log("error n")
            $("#timeError").text("");
            $("#saveBtn").removeAttr('disabled');
        }
    })

</script>