HalloDoc/Controllers/PartnersMenuController.cs
    using AspNetCoreHero.ToastNotification.Abstractions;
using HalloDoc.BussinessAccess.Repository.Interface;
using HalloDoc.DataAccess.Data;
using HalloDoc.DataAccess.Models;
using HalloDoc.DataAccess.ViewModel.PartnersMenu;
using HalloDoc.Services;
using HalloDoc.DataAccess.utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IdentityModel.Tokens.Jwt;

namespace HalloDoc.Controllers
{
    [CustomAuth("Admin")]
    public class PartnersMenuController : Controller
    {
        private readonly IPartnersRepository _partnersRepo;
        private readonly ILoginRepository _loginRepo;
        private readonly INotyfService _noty;

        public PartnersMenuController(IPartnersRepository partnersRepo, INotyfService noty, ILoginRepository loginRepo)
        {
            _partnersRepo = partnersRepo;
            _noty = noty;
            _loginRepo = loginRepo;
        }

        public string GetAdminName()
        {
            var token = Request.Cookies["jwt"];
            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
            string fname = jwt.Claims.First(c => c.Type == "firstName").Value;
            string lname = jwt.Claims.First(c => c.Type == "lastName").Value;

            return fname + "_" + lname;
        }


        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public async Task<IActionResult> Partners()
        {
            ViewBag.AdminName = GetAdminName();

            var data = _partnersRepo.Partners();

            return View(data);
        }

        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public async Task<IActionResult> VendorTable(int pageIndex, string name, int regionId)
        {
            var data = _partnersRepo.GetVendors();
            if (name != null)
            {
                data = data.Where(x => x.BusinessName.ToUpper().Contains(name.ToUpper()));
            }
            if (regionId != 0)
            {
                data = data.Where(x => x.regionId == regionId);
            }

            if (pageIndex < 1)
            {
                pageIndex = 1;
            }
            var pageSize = 4;
            data = data.OrderBy(x => x.BusinessName);
            return PartialView("_Vendorstable", await PaginatedList<VendorFormViewModel>.CreateAsync(data, pageIndex, pageSize));
        }

        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public IActionResult AddVendors()
        {
            ViewBag.AdminName = GetAdminName();
            var data = new VendorFormViewModel()
            {
                Healthprofessionaltypes = _partnersRepo.healthprofessionaltypes(),
                regions = _partnersRepo.regions()
            };
            return View(data);
        }

        [HttpPost]
        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public IActionResult AddVendors(VendorFormViewModel obj)
        {

            if (_loginRepo.isEmailAvailable(obj.Email))
            {
                _noty.Error("Email Already Registerd");
                obj.Healthprofessionaltypes = _partnersRepo.healthprofessionaltypes();

                return View(obj);
            }

            bool x = _partnersRepo.AddVendors(obj);

            if (x)
            {
                _noty.Success("Created Vendor");
            }
            else
            {
                _noty.Error("Something Went Wrong.");
            }

            return RedirectToAction("Partners");
        }

        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public IActionResult UpdateVendors(int id)
        {
            ViewBag.AdminName = GetAdminName();
            var data = _partnersRepo.UpdateVendors(id);
            return View(data);
        }
        [HttpPost]
        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public IActionResult UpdateVendors(VendorFormViewModel obj, int id)
        {
            ViewBag.AdminName = GetAdminName();

            if(_partnersRepo.GetVendorEmail(id) != obj.Email && _loginRepo.isEmailAvailable(obj.Email))
            {
                _noty.Error("Email is already registered.");
                obj.Healthprofessionaltypes = _partnersRepo.healthprofessionaltypes();
                return View(obj);
            }

            bool x = _partnersRepo.UpdateVendors(obj, id);
            if (x)
            {
                _noty.Success("Updated Vendor");
            }
            else
            {
                _noty.Error("Something Went Wrong.");
            }
            return RedirectToAction("Partners");
        }

        [RoleAuth((int)enumsFile.adminRoles.Vendersinfo)]
        public IActionResult DeleteVendors(int id)
        {
            bool x = _partnersRepo.DeleteVendors(id);

            if (x)
            {
                _noty.Success("Vendor deleted");
            }
            else
            {
                _noty.Error("Something Went Wrong.");
            }

            return RedirectToAction("Partners");
        }
    }
}

HalloDoc/Controllers/RecordsMenuController.cs
    using AspNetCoreHero.ToastNotification.Abstractions;
using HalloDoc.BussinessAccess.Repository.Interface;
using HalloDoc.DataAccess.ViewModel.AdminViewModel;
using HalloDoc.DataAccess.ViewModel.RecordsMenu;
using HalloDoc.Services;
using HalloDoc.DataAccess.utils;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Drawing.Printing;
using System.IdentityModel.Tokens.Jwt;
using System.Reflection;

namespace HalloDoc.Controllers
{
    [CustomAuth("Admin")]
    public class RecordsMenuController : Controller
    {
        private readonly IRecordsRepository _recordsRepo;
        private readonly ICommonRepository _common;
        private readonly INotyfService _noty;
        private readonly IJwtService _jwtService;
        public RecordsMenuController(IRecordsRepository recordsRepo, INotyfService noty, IJwtService jwtService, ICommonRepository common)
        {
            _recordsRepo = recordsRepo;
            _noty = noty;
            _jwtService = jwtService;
            _common = common;

        }

        [RoleAuth((int)enumsFile.adminRoles.PatientRecords)]
        public FileResult Export(SearchSortingVM obj)
        {
            var data = _recordsRepo.SearchRecords();

            if (obj != null)
            {
                if (obj.Phonenumber != null)
                {
                    data = data.Where(x => x.PhoneNumber == obj.Phonenumber);
                }
                if (obj.ProviderName != null)
                {
                    data = data.Where(x => x.Physician.ToUpper().Contains(obj.ProviderName.ToUpper()));
                }
                if (obj.PatientName != null)
                {
                    data = data.Where(x => x.PatientName.ToUpper().Contains(obj.PatientName.ToUpper()));
                }
                if (obj.Email != null)
                {
                    data = data.Where(x => x.Email == obj.Email);
                }
                if (obj.ReqStatus != null && obj.ReqStatus != 0)
                {
                    data = data.Where(x => x.ReqStatusId == obj.ReqStatus);
                }
                if (obj.ReqType != null && obj.ReqType != 0)
                {
                    data = data.Where(x => x.ReqTypeId == obj.ReqType);
                }
                if (obj.Date1.Month != 1 && obj.Date1.Year != 1 && obj.Date1.Day != 1)
                {
                    data = data.Where(x => x.DateOfService.Year >= obj.Date1.Year &&
                    x.DateOfService.Month >= obj.Date1.Month &&
                    x.DateOfService.Day >= obj.Date1.Day
                    );
                }
                if (obj.Date2.Month != 1 && obj.Date2.Year != 1 && obj.Date2.Day != 1)
                {
                    data = data.Where(x => x.DateOfService.Year <= obj.Date2.Year &&
                    x.DateOfService.Month <= obj.Date2.Month &&
                    x.DateOfService.Day <= obj.Date2.Day
                    );
                }
            }
            byte[] excelBytes = _common.fileToExcel(data);
            return File(excelBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "sheet.xlsx");
        }


        public string GetAdminName()
        {
            var token = Request.Cookies["jwt"];
            var jwt = new JwtSecurityTokenHandler().ReadJwtToken(token);
            string fname = jwt.Claims.First(c => c.Type == "firstName").Value;
            string lname = jwt.Claims.First(c => c.Type == "lastName").Value;

            return fname + "_" + lname;
        }

        [RoleAuth((int)enumsFile.adminRoles.PatientRecords)]
        public IActionResult SearchRecords()
        {
            ViewBag.AdminName = GetAdminName();

            return View();
        }

        [RoleAuth((int)enumsFile.adminRoles.PatientRecords)]
        public async Task<IActionResult> SearchRecordsTable(int pagenumber, SearchSortingVM obj)
        {
            if (pagenumber < 1)
            {
                pagenumber = 1;
            }
            var pageSize = 5;

            var data = _recordsRepo.SearchRecords();

            if (obj != null)
            {
                if (obj.Phonenumber != null)
                {
                    data = data.Where(x => x.PhoneNumber == obj.Phonenumber);
                }
                if (obj.ProviderName != null)
                {
                    data = data.Where(x => x.Physician.ToUpper().Contains(obj.ProviderName.ToUpper()));
                }
                if (obj.PatientName != null)
                {
                    data = data.Where(x => x.PatientName.ToUpper().Contains(obj.PatientName.ToUpper()));
                }
                if (obj.Email != null)
                {
                    data = data.Where(x => x.Email == obj.Email);
                }
                if (obj.ReqStatus != null && obj.ReqStatus != 0)
                {
                    data = data.Where(x => x.ReqStatusId == obj.ReqStatus);
                }
                if (obj.ReqType != null && obj.ReqType != 0)
                {
                    data = data.Where(x => x.ReqTypeId == obj.ReqType);
                }
                if (obj.Date1.Month != 1 && obj.Date1.Year != 1 && obj.Date1.Day != 1)
                {
                    data = data.Where(x => x.DateOfService >= obj.Date1);
                }
                if (obj.Date2.Month != 1 && obj.Date2.Year != 1 && obj.Date2.Day != 1)
                {
                    data = data.Where(x => x.DateOfService <= obj.Date2);
                }
            }

            return PartialView("_SearchRecordsTable", await PaginatedList<SearchTableVM>.CreateAsync(data, pagenumber, pageSize));
        }

        [RoleAuth((int)enumsFile.adminRoles.PatientRecords)]
        public IActionResult DeleteRecord(int id)
        {
            bool x = _recordsRepo.DeleteRecords(id);
            if (x)
            {
                _noty.Success("Records Deleted");
            }
            else
            {
                _noty.Error("Something went wrong.");
            }
            return RedirectToAction("SearchRecords");
        }

        [RoleAuth((int)enumsFile.adminRoles.PatientRecords)]
        public IActionResult BlockHistory()
        {
            ViewBag.AdminName = GetAdminName();
            return View();
        }

        [RoleAuth((int)enumsFile.adminRoles.BlockedHistory)]
        public async Task<IActionResult> BlockHistoryTable(int pagenumber, SearchSortingVM obj)
        {
            if (pagenumber < 1)
            {
                pagenumber = 1;
            }
            var pageSize = 5;

            var data = _recordsRepo.BlockHistory();

            if (obj != null)
            {
                if (obj.Phonenumber != null)
                {
                    data = data.Where(x => x.PhoneNumber == obj.Phonenumber);
                }
                if (obj.PatientName != null)
                {
                    data = data.Where(x => x.PatientName.ToUpper().Contains(obj.PatientName.ToUpper()));
                }
                if (obj.Email != null)
                {
                    data = data.Where(x => x.Email == obj.Email);
                }
                if (obj.Date1.Month != 1 && obj.Date1.Year != 1 && obj.Date1.Day != 1)
                {
                    data = data.Where(x => x.CreatedDate.Year == obj.Date1.Year &&
                    x.CreatedDate.Month == obj.Date1.Month &&
                    x.CreatedDate.Day == obj.Date1.Day
                    );
                }
            }
            return PartialView("_BlockHistoryTable", await PaginatedList<BlockHistoryVM>.CreateAsync(data, pagenumber, pageSize));
        }

        [RoleAuth((int)enumsFile.adminRoles.BlockedHistory)]
        public IActionResult UnBlockPatient(int id)
        {
            bool x = _recordsRepo.UnBlock(id);

            if (x)
            {
                _noty.Success("User Unblocked");
            }
            else
            {
                _noty.Error("Something went wrong.");
            }

            return RedirectToAction("BlockHistory");
        }

        [RoleAuth((int)enumsFile.adminRoles.EmailLogs)]
        public IActionResult EmailLogs()
        {
            ViewBag.AdminName = GetAdminName();
            var data = new SearchMenuVM
            {
                roles = _recordsRepo.roles()
            };
            return View(data);
        }

        [RoleAuth((int)enumsFile.adminRoles.SMSLogs)]
        public IActionResult SmsLogs()
        {
            ViewBag.AdminName = GetAdminName();
            var data = new SearchMenuVM
            {
                roles = _recordsRepo.roles()
            };
            return View(data);
        }

        [RoleAuth((int)enumsFile.adminRoles.EmailLogs)]
        public async Task<IActionResult> EmailLogTable(int pagenumber, SearchSortingVM obj)
        {
            if (pagenumber < 1)
            {
                pagenumber = 1;
            }
            var pageSize = 10;

            var data = _recordsRepo.EmailLogs();

            if (obj != null)
            {
                if (obj.Email != null)
                {
                    data = data.Where(x => x.EmailId == obj.Email);
                }
                if (obj.PatientName != null)
                {
                    data = data.Where(x => x.Recipient.ToUpper().Contains(obj.PatientName.ToUpper()));
                }
                if (obj.RoleId != 0 && obj.RoleId != null)
                {
                    data = data.Where(x => x.RoleId == obj.RoleId);
                }
                if (obj.Date1.Month != 1 && obj.Date1.Year != 1 && obj.Date1.Day != 1)
                {
                    data = data.Where(x => x.CreateDate.Year == obj.Date1.Year &&
                    x.CreateDate.Month == obj.Date1.Month &&
                    x.CreateDate.Day == obj.Date1.Day
                    );
                }

HalloDoc/Views/Shared/_ChatView.cshtml
@model Chat;
<div class="container chatNav d-flex justify-content-between">
    <p class="nameOfuser my-auto ">@Model.Receiver</p>
    <a class="closebtn" onclick="closeChatBox()">×</a>

</div>
<div class="container mt-4" style="">
    <input asp-for="reqClientId" value="@Model.reqClientId" id="reqClientId" type="number" hidden />
    <input asp-for="SenderId" value="@Model.SenderId" id="SenderId" type="number" hidden />
    <input asp-for="SenderId" value="@Model.ReceiverId" id="ReceiverId" type="number" hidden />
    <input asp-for="AccountTypeOfSender" value="@Model.AccountTypeOfSender" id="AccountTypeOfSender" type="number" hidden />
    <input asp-for="AccountTypeOfReceiver" value="@Model.AccountTypeOfReceiver" id="AccountTypeOfReceiver" type="number" hidden />
    <input asp-for="Sender" type="text" class="form-control" id="userInput" value="@Model.Sender" hidden />
    <div class="row p-1 msgContainer" id="msgContainer">
        <div class="col-12">
            <ul id="messagesList" class="list-unstyled d-flex flex-column">
                @if (Model.chatHistories != null)
                {
                    var date = DateOnly.MinValue;
                    @foreach (var item in Model.chatHistories)
                    {
                        <li class="p-1 w-100">
                            @if (date == DateOnly.MinValue)
                            {
                                date = item.CreatedOn;
                                <div class="d-flex justify-content-center dateDiv">
                                    <span>
                                        @date.Day/@date.Month/@date.Year
                                    </span>
                                </div>
                            }
                            @if (date != item.CreatedOn)
                            {
                                date = item.CreatedOn;
                                <div class="d-flex justify-content-center dateDiv">
                                   <span>
                                        @date.Day/@date.Month/@date.Year
                                   </span> 
                                </div>
                            }
                            <div class="@(item.isMyMsg ? "rightMsg" : "leftMsg")">
                                <span class="border m-1 p-2 px-3 w-auto msgSpan" >@*<b>@item.Sender:</b> *@   @item.Message </span>
                            </div>
                            <span style="font-size: 10px;" class="timeSpan mx-1 d-flex @(item.isMyMsg ? "justify-content-end" : "")">@item.CreatedAt</span>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</div>
<div class="row p-1 w-100" id="MessageBox">
    <div class="col-11 ">
        <input type="text" class="w-100 ms-1 form-control" id="messageInput" placeholder="Type a message" />
    </div>
    <div class="col-1 text-end">
        <button class="btn btn-primary" id="sendButton" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
                <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z" />
            </svg>
        </button>
    </div>
</div>
<script src="~/js/chat.js" defer></script>
<script>
    $(document).ready(function () {
        $("#msgContainer").scrollTop(1000000);
    })
</script>

HalloDoc/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HalloDoc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/HeaderFooter.css" />

    <!-- js ans css for phone input -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    @* Multi select option *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    @RenderSection("Styles", required: false)

    <link rel="stylesheet" href="~/css/AdminDashboard.css" />
</head>

<body>
    <div class="main" style="overflow-x: hidden;">
        <span class="loader " id="loader"></span>
        <header id="header" class="shadow-lg w-100 border-bottom">
            @if (ViewBag.AdminName != null)
            {
                <a id="listImg" class="btn border d-md-none mt-3 mb-3" onclick="openNav()">
                    <img src="~/images/list.svg" alt="">
                </a>
            }

            <img src="~/images/logo.png" class="" height="80%" alt="">

            <div class="float-end d-flex">
                @if (ViewBag.AdminName != null)
                {
                    <h4 class="m-auto d-none d-md-block">Welcome <b>@ViewBag.AdminName</b></h4>
                    <a id="logout-btn"
                       asp-controller="Home" asp-action="logout"
                       class="btn mt-3 mb-3 me-1 m-md-3 m-lg-4 float-end"
                       style="color: #01bce9; border: 1px solid #01bce9;">
                        <span class="d-none d-md-block">Log Out</span>
                        <img id="logoutImg" src="~/images/box-arrow-right.svg" class="d-md-none">
                    </a>

                }
                <a id="light-dark-btn" class="btn border border-black mt-3 mb-3 m-md-3 m-lg-4">
                    <img src="~/images/dark_mode_black_24dp.svg" alt="">
                </a>
            </div>
        </header>
        <nav id="adminNav">
            <ul class="d-none d-md-flex nav w-100 border-bottom" id="togglebar">
                <li class="nav-item ms-3 me-1">
                    <a class="nav-link" id="DashboardLink" href="@Url.Action("Dashboard", "AdminDashboard")">Dashboard</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("ProviderLocation", "ProvidersMenu")">Provider Location</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("MyProfile", "AdminDashboard")">My Profile</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Providers
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Provider", "AdminDashboard")">Providers</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Scheduling", "ProvidersMenu")">Scheduling</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Invoicing", "ProvidersMenu")">Invoicing</a></li>
                    </ul>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("Partners", "PartnersMenu")">Partners</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Access
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="nav-link" href="@Url.Action("Access", "AdminDashboard")">Account Access</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("UserAccess", "AdminDashboard")">User Access</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("CreateAdmin", "AdminDashboard")">Create Admin</a></li>
                    </ul>
                </li>
                <li class="nav-item ">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Records
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="nav-link" href="@Url.Action("SearchRecords", "RecordsMenu")">Search Records</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("EmailLogs", "RecordsMenu")">Email Logs</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("SmsLogs", "RecordsMenu")">SMS Logs</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("PatientHistory", "RecordsMenu")">Patient Records</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("BlockHistory", "RecordsMenu")">Blocked History</a></li>
                    </ul>
                </li>
            </ul>

        </nav>

        <div id="mySidebar" class="sidebar">
            <p class="p1">Welcome</p>
            <a class="closebtn" onclick="closeNav()">×</a>
            <b class="nameOfuser">@ViewBag.AdminName</b>
            <ul class="d-md-none w-100">
                <li class="nav-item pe-1">
                    <a class="nav-link" id="DashboardLink" href="@Url.Action("Dashboard", "AdminDashboard")">Dashboard</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("ProviderLocation", "ProvidersMenu")">Provider Location</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("MyProfile", "AdminDashboard")">My Profile</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" role="button" href="#collapseExample" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseExample">
                        Providers
                    </a>
                    <ul class="collapse" id="collapseExample">
                        <li><a class="dropdown-item" href="@Url.Action("Provider", "AdminDashboard")">Providers</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Scheduling", "ProvidersMenu")">Scheduling</a></li>
                        <li><a class="dropdown-item" href="#">Invoicing</a></li>
                    </ul>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" href="@Url.Action("Partners", "PartnersMenu")">Partners</a>
                </li>
                <li class="nav-item pe-1">
                    <a class="nav-link" role="button" href="#collapse2" data-bs-toggle="collapse" aria-expanded="false">
                        Access
                    </a>
                    <ul class="collapse" id="collapse2">
                        <li><a class="nav-link" href="@Url.Action("Access", "AdminDashboard")">Account Access</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("UserAccess", "AdminDashboard")">User Access</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("CreateAdmin", "AdminDashboard")">Create Admin</a></li>
                    </ul>

                <li class="nav-item ">
                    <a class="nav-link" role="button" data-bs-toggle="collapse" href="#collapse3" aria-expanded="false">
                        Records
                    </a>
                    <ul class="collapse" id="collapse3">
                        <li><a class="nav-link" href="@Url.Action("SearchRecords", "RecordsMenu")">Search Records</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("EmailLogs", "RecordsMenu")">Email Logs</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("SmsLogs", "RecordsMenu")">SMS Logs</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("PatientHistory", "RecordsMenu")">Patient Records</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("BlockHistory", "RecordsMenu")">Blocked History</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div id="myChatBox" class="sidebarChat">
        </div>
        @RenderBody()
    </div>

    <footer id="footer" class="footer w-100 mt-auto bg-dark shadow">
        <span class="border-end border-white border-2 pe-3">Terms and Conditions</span>
        <span class="ps-3">Privacy Policy</span>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/microsoft-signalr/signalr.js" defer></script>
    
    <script>
        //dark mode

        document.getElementById('light-dark-btn').addEventListener('click', () => {
            if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
                localStorage.setItem("PageTheme", "light");
                document.documentElement.setAttribute('data-bs-theme', 'light')
            }
            else {
                localStorage.setItem("PageTheme", "dark");
                document.documentElement.setAttribute('data-bs-theme', 'dark')
            }
        })
        if (localStorage.getItem("PageTheme") === "light") {
            document.documentElement.setAttribute('data-bs-theme', 'light')
        }
        else {
            document.documentElement.setAttribute('data-bs-theme', 'dark')
        }
        function openNav() {
            document.getElementById("mySidebar").style.width = "45vw";
        }

        function closeNav() {

            document.getElementById("mySidebar").style.width = "0px";
        }

        function openChatBox() {
            document.getElementById("myChatBox").style.width = "45vw";
        }
        //function closeChatBox() {
        //    document.getElementById("myChatBox").style.width = "0px";
        //    document.getElementById("myChatBox").innerHTML = "";
        //    connection.off("SendSaleUpdate");
        //}

    </script>
    
    <script src="~/js/admin.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>



    @RenderSection("AdminScript", required: false)
    @await Component.InvokeAsync("Notyf")
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
</body>

</html>